version: "3.8"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  json-server:
    image: typicode/json-server
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:3000"
